### ISSUE TITLE
dockerfile no longer works

### ISSUE THREAD

**Issue by ekc438** [IBM/db2-jupyter#7]
When I use the docker file exactly as supplied along with the build command exactly as specified, it fails with:
`#5 62.35 /bin/sh: 1: easy_install: not found`

It appears easy_install has been not just deprecated, but removed. I altered the docker file to use pip instead (alternate docker file attached), but then get a different set of errors:
`#5 72.14 Collecting ibm-db
#5 72.26   Downloading ibm_db-3.1.1.tar.gz (1.1 MB)
#5 72.74      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.3 MB/s eta 0:00:00
#5 73.16   Installing build dependencies: started
#5 78.03   Installing build dependencies: finished with status 'done'
#5 78.04   Getting requirements to build wheel: started
#5 78.73   Getting requirements to build wheel: finished with status 'error'
#5 78.74   error: subprocess-exited-with-error
#5 78.74
#5 78.74   × Getting requirements to build wheel did not run successfully.
#5 78.74   │ exit code: 1
#5 78.74   ╰─> [30 lines of output]
#5 78.74       Detected 64-bit Python
#5 78.74       Downloading https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
#5 78.74       Traceback (most recent call last):
#5 78.74         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#5 78.74           main()
#5 78.74         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#5 78.74           json_out['return_val'] = hook(**hook_input['kwargs'])
#5 78.74         File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
#5 78.74           return hook(config_settings)
#5 78.74         File "/tmp/pip-build-env-whwx5onc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
#5 78.74           return self._get_build_requires(
#5 78.74         File "/tmp/pip-build-env-whwx5onc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
#5 78.74           self.run_setup()
#5 78.74         File "/tmp/pip-build-env-whwx5onc/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
#5 78.74           exec(compile(code, __file__, 'exec'), locals())
#5 78.74         File "setup.py", line 241, in <module>
#5 78.74           file_stream = BytesIO(request.urlopen(url, context=context).read())
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 214, in urlopen
#5 78.74           return opener.open(url, data, timeout)
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 523, in open
#5 78.74           response = meth(req, response)
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 632, in http_response
#5 78.74           response = self.parent.error(
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 561, in error
#5 78.74           return self._call_chain(*args)
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 494, in _call_chain
#5 78.74           result = func(*args)
#5 78.74         File "/opt/conda/lib/python3.9/urllib/request.py", line 641, in http_error_default
#5 78.74           raise HTTPError(req.full_url, code, msg, hdrs, fp)
#5 78.74       urllib.error.HTTPError: HTTP Error 500: Internal Server Error
#5 78.74       [end of output]
#5 78.74
#5 78.74   note: This error originates f
[db2jupyter.docker.txt](https://github.com/IBM/db2-jupyter/files/8005247/db2jupyter.docker.txt)
rom a subprocess, and is likely not a problem with pip.
#5 78.74 error: subprocess-exited-with-error
#5 78.74
#5 78.74 × Getting requirements to build wheel did not run successfully.
#5 78.74 │ exit code: 1
#5 78.74 ╰─> See above for output.
#5 78.74
#5 78.74 note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c conda update -y conda &&     conda install -y -c conda-forge ipywidgets qgrid &&     apt-get update &&     apt-get install -y gcc  &&     pip install --upgrade setuptools pip &&     pip install ibm-db &&     rm -rf /var/lib/apt/lists/*]: exit code: 1`

**Comment by ekc438** [comment]
Found a solution, opened a PR for it: https://github.com/IBM/db2-jupyter/pull/8
